name:UpdateGitHubStatsImages

on:
schedule:
-cron:"00***"#RunsdailyatmidnightUTC
workflow_dispatch:#Allowsmanualtrigger

jobs:
update-stats:
runs-on:ubuntu-latest
permissions:
contents:write

steps:
-uses:actions/checkout@v3

-name:GenerateREADMEwithUpdatedStats
run:|
cat>README.md<<'EOL'
---

###GitHubStats
<palign="center">
<imgsrc="https://github-readme-stats.vercel.app/api?username=raimonvibe&show_icons=true&theme=radical&include_all_commits=true&count_private=true"alt="Raimon'sGitHubStats"/>
<imgsrc="https://github-readme-streak-stats.herokuapp.com/?user=raimonvibe&theme=radical"alt="Raimon'sGitHubStreakStats"/>
</p>

<palign="center">
<strong>GitHubActivity:</strong><br>
${{github.public_repos}}PublicRepositories<br>
ヂ${{github.followers}}Followers路Following${{github.following}}Developers<br>
MembersinceAugust2016
</p>

---
EOL

-name:CommitandPushChanges
run:|
gitconfig--localuser.email"action@github.com"
gitconfig--localuser.name"GitHubAction"
gitaddREADME.md
gitcommit-m"UpdateGitHubStats"
gitpushname:UpdateGitHubStatsImages

on:
schedule:
-cron:"00***"#RunsdailyatmidnightUTC
workflow_dispatch:#Allowsmanualtrigger

jobs:
update-stats:
runs-on:ubuntu-latest
permissions:
contents:write

steps:
-uses:actions/checkout@v3

-name:GenerateREADMEwithUpdatedStats
run:|
cat>README.md<<'EOL'
---

###GitHubStats
<palign="center">
<imgsrc="https://github-readme-stats.vercel.app/api?username=raimonvibe&show_icons=true&theme=radical&include_all_commits=true&count_private=true"alt="Raimon'sGitHubStats"/>
<imgsrc="https://github-readme-streak-stats.herokuapp.com/?user=raimonvibe&theme=radical"alt="Raimon'sGitHubStreakStats"/>
</p>

<palign="center">
<strong>GitHubActivity:</strong><br>
${{github.public_repos}}PublicRepositories<br>
ヂ${{github.followers}}Followers路Following${{github.following}}Developers<br>
MembersinceAugust2016
</p>

---
EOL

-name:CommitandPushChanges
run:|
gitconfig--localuser.email"action@github.com"
gitconfig--localuser.name"GitHubAction"
gitaddREADME.md
gitcommit-m"UpdateGitHubStats"
gitpushname:UpdateGitHubStatsImages

on:
schedule:
-cron:"00***"#RunsdailyatmidnightUTC
workflow_dispatch:#Allowsmanualtrigger

jobs:
update-stats:
runs-on:ubuntu-latest
permissions:
contents:write

steps:
-uses:actions/checkout@v3

-name:GenerateREADMEwithUpdatedStats
run:|
cat>README.md<<'EOL'
---

###GitHubStats
<palign="center">
<imgsrc="https://github-readme-stats.vercel.app/api?username=raimonvibe&show_icons=true&theme=radical&include_all_commits=true&count_private=true"alt="Raimon'sGitHubStats"/>
<imgsrc="https://github-readme-streak-stats.herokuapp.com/?user=raimonvibe&theme=radical"alt="Raimon'sGitHubStreakStats"/>
</p>

<palign="center">
<strong>GitHubActivity:</strong><br>
${{github.public_repos}}PublicRepositories<br>
ヂ${{github.followers}}Followers路Following${{github.following}}Developers<br>
MembersinceAugust2016
</p>

---
EOL

-name:CommitandPushChanges
run:|
gitconfig--localuser.email"action@github.com"
gitconfig--localuser.name"GitHubAction"
gitaddREADME.md
gitcommit-m"UpdateGitHubStats"
gitpushname:UpdateGitHubStatsImages

on:
schedule:
-cron:"00***"#RunsdailyatmidnightUTC
workflow_dispatch:#Allowsmanualtrigger

jobs:
update-stats:
runs-on:ubuntu-latest
permissions:
contents:write

steps:
-uses:actions/checkout@v3

-name:GenerateREADMEwithUpdatedStats
run:|
cat>README.md<<'EOL'
---

###GitHubStats
<palign="center">
<imgsrc="https://github-readme-stats.vercel.app/api?username=raimonvibe&show_icons=true&theme=radical&include_all_commits=true&count_private=true"alt="Raimon'sGitHubStats"/>
<imgsrc="https://github-readme-streak-stats.herokuapp.com/?user=raimonvibe&theme=radical"alt="Raimon'sGitHubStreakStats"/>
</p>

<palign="center">
<strong>GitHubActivity:</strong><br>
${{github.public_repos}}PublicRepositories<br>
ヂ${{github.followers}}Followers路Following${{github.following}}Developers<br>
MembersinceAugust2016
</p>

---
EOL

-name:CommitandPushChanges
run:|
gitconfig--localuser.email"action@github.com"
gitconfig--localuser.name"GitHubAction"
gitaddREADME.md
gitcommit-m"UpdateGitHubStats"
gitpush
